#!/bin/bash
# Clean up the repository by removing auxiliary files.

FILES=(PythonEssentials DataScienceEssentials Volume1 Volume2 Volume3 Volume4 GettingStarted ExtraLabs onelab)

set +e      # Ignore any failures

# Delete .pyc files and Jupyter Notebook checkpoints.
find . -type f -name "*.pyc" -delete
find . -type d -name ".ipynb_checkpoints" -exec rm -rf {} +
find . -type d -name "__pycache__" -exec rm -rf {} +

# Delete extra files that may have been generated by LaTeX.
for FILE in ${FILES[@]}
do
    find . -type f -name "$FILE*.*" ! -name "$FILE.tex" ! -name "$FILE.pdf" -delete
done

