#!/bin/bash
# Compile the main tex files and ensure that there are no errors.

USAGE="usage: ./.compile_labs.sh [LaTeX compiler, defaults to pdflatex]"
MAX_TIME=15

set -e
echo

# Select a program to compile LaTeX files (deault pdflatex).
if [ "$#" -eq 0 ]; then
    COMPILER="pdflatex -halt-on-error"
else
    COMPILER=""
    for arg in "$@"
    do
        if [ ${#COMPILER} -ne 0 ]; then
            COMPILER+=" "
        fi
        COMPILER+=$arg
    done
fi

# Check that the compile command exists.
command -v $COMPILER > /dev/null 2>&1 || { echo "This script requires $COMPILER but it's not installed. Aborting."; exit 1; }

# Check for large files.
python travis_pre.py

for FILE in PythonEssentials Volume1 Volume2 Volume3 Volume4
do
    # Compile the tex file twice in 20 seconds or less each time.
    echo -n "Compiling $FILE.tex..."
    if ! perl -e "alarm $MAX_TIME; exec @ARGV" "eval $COMPILER $FILE.tex > /dev/null"; then
        echo -e "\n\nFAILURE: $FILE.tex could not be compiled\n"
        exit 1
    fi
    if ! perl -e "alarm $MAX_TIME; exec @ARGV" "eval $COMPILER $FILE.tex > /dev/null"; then
        echo -e "\n\nFAILURE: $FILE.tex could not be compiled\n"
        exit 1
    fi

    # Check that the PDF files exist.
    if [ ! -e $FILE.pdf ]; then
        echo -e "\nFAILURE: $FILE.pdf does not exist\n"
        exit 1
    else
        echo "success"
    fi

    # Remove auxiliary files generated by compiling LaTeX.
    set +e
    find . -type f -name "$FILE.*" ! -name "$FILE.tex" ! -name "$FILE.pdf" -delete
    set -e

done

echo -e "\nVALIDATION SUCCESSFUL\n"
