# tests.yml: GitHub action to run tests and ensure latex files compile.
name: CI
on: push
jobs:
  # First job: compile LaTeX files.
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile main TeX files
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            GettingStarted.tex
            PythonEssentials.tex
            DataScienceEssentials.tex
            Volume1.tex
            Volume2.tex
            Volume3.tex
            Volume4.tex
          compiler: latexmk
          args: -pdf -g -file-line-error -interaction=nonstopmode -Werror
          post_compile: tar -vzcf labs.tar.gz GettingStarted.pdf PythonEssentials.pdf DataScienceEssentials.pdf Volume1.pdf Volume2.pdf Volume3.pdf Volume4.pdf
      - name: Upload compiled PDF files
        uses: actions/upload-artifact@v2
        with:
          name: compiled-labs
          path: labs.tar.gz
